export const films = [
    { id: 0, src: "/img/film_1.png", name: "Fantastic Beasts", year: 2018, ranking: 5.7, genre: ["Adventure","Family","Fantasy"] },
    { id: 1, src: "/img/film_2.png", name: "AssAssin’s Creed", year: 2018, ranking: 7, genre: ["Action","Adventure","Fantasy"] },
    { id: 2, src: "/img/film_3.png", name: "Now you see me 2", year: 2020, ranking: 7.8, genre: ["Action","Adventure","Comedy"] },
    { id: 3, src: "/img/film_4.png", name: "The Legend of Tarzan", year: 2020, ranking: 8.9, genre: ["Action","Adventure","Drama"] },
    { id: 4, src: "/img/film_5.png", name: "Doctor Strange", year: 2019, ranking: 7.2, genre: ["Action","Adventure","Fantasy"] },
    { id: 5, src: "/img/film_6.png", name: "Captain America", year: 2021, ranking: 6.9, genre: ["Action","Adventure","Sci-Fi"] },
    {id: 6, src: "/img/film_7.png", name: "alice through the looking glass", year: 2016, ranking: 6.6, genre: ["Adventure","Family","Fantasy"]},
    {id: 7, src: "/img/film_8.png", name: "Finding Dory", year: 2018, ranking: 8.1, genre: ["Animation","Family","Comedy"]},
    {id: 8, src: "/img/film_9.png", name: "The BFG", year: 2017, ranking: 6.4, genre: ["Adventure","Family","Fantasy"]},
    {id: 9, src: "/img/film_10.png", name: "Independence Day", year: 1996, ranking: 9.1, genre: ["Action","Sci-Fi"]},
    {id: 10, src: "/img/film_11.png", name: "ice age collision course", year: 2016, ranking: 8.7, genre: ["Adventure","Comedy","Family"]},
    {id: 11, src: "/img/film_12.png", name: "Moana", year: 2017, ranking: 8.3, genre: ["Action","Fantasy","Family"]},
    { id: 12, src: "/img/film_1.png", name: "Fantastic Beasts", year: 2018, ranking: 5.7, genre: ["Adventure","Family","Fantasy"] },
    { id: 13, src: "/img/film_2.png", name: "AssAssin’s Creed", year: 2018, ranking: 7, genre: ["Action","Adventure","Fantasy"] },
    { id: 14, src: "/img/film_3.png", name: "Now you see me 2", year: 2020, ranking: 7.8, genre: ["Action","Adventure","Comedy"] },
    { id: 15, src: "/img/film_4.png", name: "The Legend of Tarzan", year: 2020, ranking: 8.9, genre: ["Action","Adventure","Drama"] },
    { id: 16, src: "/img/film_5.png", name: "Doctor Strange", year: 2019, ranking: 7.2, genre: ["Action","Adventure","Fantasy"] },
    { id: 17, src: "/img/film_6.png", name: "Captain America", year: 2021, ranking: 6.9, genre: ["Action","Adventure","Sci-Fi"] },
    {id: 18, src: "/img/film_7.png", name: "alice through the looking glass", year: 2016, ranking: 6.6, genre: ["Adventure","Family","Fantasy"]},
    {id: 19, src: "/img/film_8.png", name: "Finding Dory", year: 2018, ranking: 8.1, genre: ["Animation","Family","Comedy"]},
    {id: 20, src: "/img/film_9.png", name: "The BFG", year: 2017, ranking: 6.4, genre: ["Adventure","Family","Fantasy"]},
    //{id: , src: , name: , year: , ranking: , genre: ["","",""]},
  ];